In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = sns.load_dataset('iris')

In [4]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df.groupby('species')['sepal_length'].agg(['mean','median','min','max','std'])

             mean  median  min  max       std
species
setosa      5.006     5.0  4.3  5.8  0.352490
versicolor  5.936     5.9  4.9  7.0  0.516171
virginica   6.588     6.5  4.9  7.9  0.635880

In [6]:
df.groupby('species')['sepal_length'].apply(list)

species
setosa        [5.1, 4.9, 4.7, 4.6, 5.0, 5.4, 4.6, 5.0, 4.4, ...
versicolor    [7.0, 6.4, 6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, ...
virginica     [6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 4.9, 7.3, 6.7, ...
Name: sepal_length, dtype: object

In [7]:
setosa = df[df['species'] == 'setosa']
versicolor = df[df['species'] == 'versicolor']
virginica = df[df['species'] == 'virginica']

In [8]:
print("Setosa:\n", setosa.describe())
print("\nVersicolor:\n", versicolor.describe())
print("\nVirginica:\n", virginica.describe())

Setosa:
        sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000    50.000000
mean        5.00600     3.428000      1.462000     0.246000
std         0.35249     0.379064      0.173664     0.105386
min         4.30000     2.300000      1.000000     0.100000
25%         4.80000     3.200000      1.400000     0.200000
50%         5.00000     3.400000      1.500000     0.200000
75%         5.20000     3.675000      1.575000     0.300000
max         5.80000     4.400000      1.900000     0.600000

Versicolor:
        sepal_length  sepal_width  petal_length  petal_width
count     50.000000    50.000000     50.000000    50.000000
mean       5.936000     2.770000      4.260000     1.326000
std        0.516171     0.313798      0.469911     0.197753
min        4.900000     2.000000      3.000000     1.000000
25%        5.600000     2.525000      4.000000     1.200000
50%        5.900000     2.800000      4.350000     1.300000
75%        6.300000     3.000000      4.600000     1.500000
max        7.000000     3.400000      5.100000     1.800000

Virginica:
        sepal_length  sepal_width  petal_length  petal_width
count      50.00000    50.000000     50.000000     50.00000
mean        6.58800     2.974000      5.552000      2.02600
std         0.63588     0.322497      0.551895      0.27465
min         4.90000     2.200000      4.500000      1.40000
25%         6.22500     2.800000      5.100000      1.80000
50%         6.50000     3.000000      5.550000      2.00000
75%         6.90000     3.175000      5.875000      2.30000
max         7.90000     3.800000      6.900000      2.50000

In [10]:
print("Setosa Percentiles:\n", setosa.select_dtypes(include='number').quantile([0.25, 0.5, 0.75]))
print("\nVersicolor Percentiles:\n", versicolor.select_dtypes(include='number').quantile([0.25, 0.5, 0.75]))
print("\nVirginica Percentiles:\n", virginica.select_dtypes(include='number').quantile([0.25, 0.5, 0.75]))

Setosa Percentiles:
       sepal_length  sepal_width  petal_length  petal_width
0.25           4.8        3.200         1.400          0.2
0.50           5.0        3.400         1.500          0.2
0.75           5.2        3.675         1.575          0.3

Versicolor Percentiles:
       sepal_length  sepal_width  petal_length  petal_width
0.25           5.6        2.525          4.00          1.2
0.50           5.9        2.800          4.35          1.3
0.75           6.3        3.000          4.60          1.5

Virginica Percentiles:
       sepal_length  sepal_width  petal_length  petal_width
0.25         6.225        2.800         5.100          1.8
0.50         6.500        3.000         5.550          2.0
0.75         6.900        3.175         5.875          2.3